/**
 * @file
 * @copyright This code is licensed under the 3-clause BSD license.\n
 *            Copyright ETH Zurich, Department of Chemistry and Applied Biosciences, Reiher Group.\n
 *            See LICENSE.txt for details.
 *
 * @note This file was generated by the Embed binary from runtime values.
 *   Prefer improving the generator over editing this file whenever possible.
 *
 */
#ifndef INCLUDE_SPARROW_IMPLEMENTATIONS_DFTB_PARAMS_MIO_1_1_PARAMETER_SET_H
#define INCLUDE_SPARROW_IMPLEMENTATIONS_DFTB_PARAMS_MIO_1_1_PARAMETER_SET_H

#include "Sparrow/Implementations/Dftb/ParameterSet.h"

namespace Scine {
namespace Sparrow {
namespace dftb {

/*! @brief Dftb mio-1-1 parameter set generator
 *
 * @param elements Elements for which to load parameters. If empty, loads all
 *   available parameters.
 */
ParameterSet params_mio_1_1(const std::vector<int>& elements = {});

// NOTE: Atom-pair data generator fns
SkfData params_mio_1_1_c_p();
SkfData params_mio_1_1_s_h();
SkfData params_mio_1_1_o_o();
SkfData params_mio_1_1_p_p();
SkfData params_mio_1_1_h_p();
SkfData params_mio_1_1_c_s();
SkfData params_mio_1_1_s_n();
SkfData params_mio_1_1_s_o();
SkfData params_mio_1_1_o_s();
SkfData params_mio_1_1_n_s();
SkfData params_mio_1_1_n_c();
SkfData params_mio_1_1_n_h();
SkfData params_mio_1_1_p_s();
SkfData params_mio_1_1_o_h();
SkfData params_mio_1_1_c_n();
SkfData params_mio_1_1_n_n();
SkfData params_mio_1_1_c_h();
SkfData params_mio_1_1_p_c();
SkfData params_mio_1_1_n_o();
SkfData params_mio_1_1_n_p();
SkfData params_mio_1_1_s_c();
SkfData params_mio_1_1_h_h();
SkfData params_mio_1_1_c_c();
SkfData params_mio_1_1_h_n();
SkfData params_mio_1_1_h_s();
SkfData params_mio_1_1_c_o();
SkfData params_mio_1_1_o_n();
SkfData params_mio_1_1_h_o();
SkfData params_mio_1_1_p_n();
SkfData params_mio_1_1_s_p();
SkfData params_mio_1_1_p_h();
SkfData params_mio_1_1_o_c();
SkfData params_mio_1_1_s_s();
SkfData params_mio_1_1_o_p();
SkfData params_mio_1_1_p_o();
SkfData params_mio_1_1_h_c();

// Spin constants
SkfSpinConstants params_mio_1_1_spin();

} // namespace dftb
} // namespace Sparrow
} // namespace Scine

#endif
