/**
 * @file
 * @copyright This code is licensed under the 3-clause BSD license.\n
 *            Copyright ETH Zurich, Department of Chemistry and Applied Biosciences, Reiher Group.\n
 *            See LICENSE.txt for details.
 *
 * @note This file was generated by the Embed binary from runtime values.
 *   Prefer improving the generator over editing this file whenever possible.
 *
 * This file contains functions generating runtime values. It was
 * generated from runtime values of its return type. It is not intended to be
 * human-readable. A small guide: Return values are directly brace-initialized
 * in deep nesting to keep file size to a minimum. Types are annotated only when
 * necessary. Floating point values are represented in hexadecimal (see
 * std::hexfloat) to ensure serialization does not cause loss of accuracy.
 *
 * The functions defined here might be declared and called elsewhere entirely.
 *
 */
#include "Sparrow/Implementations/Nddo/Parameters.h"

namespace Scine {
namespace Sparrow {
namespace nddo {

Parameters am1() {
  // clang-format off
  using Pack = Parameters::Atomic::Pack;
  using Spd = Parameters::Atomic::Pack::Spd;
  using Gauss = Parameters::Atomic::GaussianRepulsion;

  return {
    {
      {19, {Pack {Spd {-0x1.10d28d6b8ded9p+2, -0x1.555ec22d3699fp+1, 0x0p+0}, Spd {-0x1.0a5b0ff10ecb7p-2, -0x1.a90dc0b2e316cp+0, 0x0p+0}, Spd {0x1.441a2cd1f0224p+0, 0x1.e9439a8983a1ep-1, 0x0p+0}, Spd {}, 0x1.4000346dc5d64p+3, 0x1.7765a06dc9313p+1, 0x1.35c622fa000bcp+2, 0x1.5df3c2dadb835p+1, 0x1.802f8f39c446fp+1, 0x1.5c4e09ce3501cp+0, 0x0p+0, 0x0p+0, 0x1.785d3854db23ap+2}, {{}}}},
      {18, {Pack {Spd {0x1.c8d188be8002fp+3, -0x1.52b488d378b88p+6, 0x0p+0}, Spd {-0x1.381162fed2d95p+1, -0x1.6fae8f0efc1c4p+4, 0x0p+0}, Spd {0x1.f15e2c0541886p-1, 0x1.7b1ca4101521p+2, 0x0p+0}, Spd {}, 0x1.d245af36b9d07p-1, 0x1.3ffd749fe50d3p+4, 0x1.05adbe2ea4584p+4, 0x1.9dc01ad7f29acp+3, 0x1.a2dfa79ae41c7p-1, 0x1.de149c3428a69p+3, 0x0p+0, 0x0p+0, 0x1.df182235b4edbp+0}, {{Gauss {0x1.967909d71956fp-2, 0x1.f046bc7cf370ap+1, 0x1.188a2ec28b2a7p+0}}}}},
      {17, {Pack {Spd {-0x1.be74aec8d5c74p+6, -0x1.328f78359bc34p+6, 0x0p+0}, Spd {-0x1.8983c4b09e98ep+4, -0x1.d46412cf0f9d3p+3, 0x0p+0}, Spd {0x1.d0d0edc3bd599p+1, 0x1.09d48cb4aec8dp+1, 0x0p+0}, Spd {}, 0x1.e0f5c28f5c28fp+3, 0x1.699999999999ap+3, 0x1.a51eb851eb852p+3, 0x1.3f0a3d70a3d71p+3, 0x1.35c28f5c28f5cp+1, 0x1.cf7b0bb9f27f9p-1, 0x0p+0, 0x0p+0, 0x1.75add9c27e953p+1}, {{Gauss {0x1.8204f2ae07e5ap-4, 0x1p+2, 0x1.4cccccccccccdp+0}, Gauss {0x1.bd1ed9dfdac69p-6, 0x1p+2, 0x1.0cccccccccccdp+1}}}}},
      {16, {Pack {Spd {-0x1.c58d6d3b6cbdap+5, -0x1.85bc842fa5094p+5, 0x0p+0}, Spd {-0x1.f5d51b4fe79eep+1, -0x1.f9f01322f2735p+2, 0x0p+0}, Spd {0x1.2ee9f6a93f291p+1, 0x1.aad1bf7ad4b27p+0, 0x0p+0}, Spd {}, 0x1.79299b6f5caf3p+3, 0x1.414202d9cf13dp+3, 0x1.1538561d4306ep+3, 0x1.f2072d1aeb3ddp+2, 0x1.441d10b1feeb3p+1, 0x1.278446a124278p+0, 0x0p+0, 0x0p+0, 0x1.3b17481b21c47p+1}, {{Gauss {-0x1.04b5350092ccfp-1, 0x1.25ff08893b7d8p+2, 0x1.8a949a5657fb7p-1}, Gauss {-0x1.84ba0e8427419p-7, 0x1.776822ff08894p+2, 0x1.80d91eeaa6d26p+0}, Gauss {0x1.942917507e9d9p-7, 0x1.b1d5b24e9c454p+3, 0x1.012c94b380cb7p+1}}}}},
      {15, {Pack {Spd {-0x1.503d28d002e23p+5, -0x1.103ee45c358bp+5, 0x0p+0}, Spd {-0x1.96a411c2a0232p+2, -0x1.a5ce2d1f1cfbcp+2, 0x0p+0}, Spd {0x1.fb352a8438088p+0, 0x1.e009d495182aap+0, 0x0p+0}, Spd {}, 0x1.71eb8f9b13166p+3, 0x1.f82a6b0d9514p+2, 0x1.4f325d4a5df22p+2, 0x1.d3b0813cab82p+2, 0x1.8ef8487b99d45p-1, 0x1.2d4d69146b9cep+0, 0x0p+0, 0x0p+0, 0x1.3a47fdc5931cap+1}, {{Gauss {-0x1.04ba0e8427419p-5, 0x1.8p+2, 0x1.796d3b6cbd988p+0}, Gauss {0x1.2e9ccb7d41744p-6, 0x1.cp+2, 0x1.c783be6601bcap+0}, Gauss {0x1.10b630a91537ap-5, 0x1.2p+3, 0x1.80d77b7c7820ap+1}}}}},
      {14, {Pack {Spd {-0x1.0fa1049235f81p+5, -0x1.cef4bb5e0f7fdp+4, 0x0p+0}, Spd {-0x1.e47607c4199fep+1, -0x1.f7d6e8af81627p+0, 0x0p+0}, Spd {0x1.d4a88effe2a3dp+0, 0x1.48f2ae07e5a79p+0, 0x0p+0}, Spd {}, 0x1.3a3d70a3d70a4p+3, 0x1.d3d70a3d70a3dp+2, 0x1.0b851eb851eb8p+3, 0x1.a28f5c28f5c29p+2, 0x1.51eb851eb851fp+0, 0x1.62b0ac5abc642p+0, 0x0p+0, 0x0p+0, 0x1.21001d5c31594p+1}, {{Gauss {0x1p-2, 0x1.2p+3, 0x1.d2a9f7b5aea31p-1}, Gauss {0x1.f7ea1c68ec52ap-5, 0x1.4p+2, 0x1.fedd9c27e9531p+0}, Gauss {0x1.549b62c77574fp-6, 0x1.4p+2, 0x1.7ecc4ef88b978p+1}}}}},
      {10, {Pack {Spd {0x1.34f936171342p+3, -0x1.1c8de679463dp+6, 0x0p+0}, Spd {-0x1.35bae7c7fad5fp-3, -0x1.7d8ff880afbddp+4, 0x0p+0}, Spd {0x1.7fe568a50507ap+2, 0x1.0ae023c1a6282p+2, 0x0p+0}, Spd {}, 0x1.fe736049ecb32p-2, 0x1.2f1f1a5ca2984p+4, 0x1.4515f0cd5d158p+3, 0x1.133a4d3897f7p+3, 0x1.350acc0bdcad1p-2, 0x1.b4b41f191fe1ap+4, 0x0p+0, 0x0p+0, 0x1.4a3c4453ece72p+1}, {{Gauss {0x1.e93392d4837a7p-3, 0x1.19f31bb63eebdp+3, 0x1.1c0ac7da1ec4ep+0}}}}},
      {11, {Pack {Spd {-0x1.448d2bcd0d647p+2, -0x1.7c3675071319cp+1, 0x0p+0}, Spd {-0x1.2333d5f061fd5p+0, -0x1.0cdf21632716cp+1, 0x0p+0}, Spd {0x1.93f8fcd67fd3fp-1, 0x1.23d62611e2809p+0, 0x0p+0}, Spd {}, 0x1.9e68a0d349be9p+2, 0x1.31cb7ffb62e25p+3, 0x1.5b57b6a03a9d9p+2, 0x1.5ad48c494efe7p+2, 0x1.6f11c1c9638bcp+1, 0x1.0cf4cf34dbffcp+1, 0x0p+0, 0x0p+0, 0x1.80000a7c5ac47p+2}, {{Gauss {0x1.b720e70054b99p-1, 0x1.512dace174fa8p+0, 0x1.0001a0e9eff34p+1}}}}},
      {6, {Pack {Spd {-0x1.a03ab10ba6267p+5, -0x1.3ce9f623076cp+5, 0x0p+0}, Spd {-0x1.f6e7b1c0010c7p+3, -0x1.ee08bb906466bp+2, 0x0p+0}, Spd {0x1.cf04ab606b7aap+0, 0x1.af63c31df761dp+0, 0x0p+0}, Spd {}, 0x1.875c28f5c28f6p+3, 0x1.628f5c28f5c29p+3, 0x1.6f0a3d70a3d71p+3, 0x1.3ae147ae147aep+3, 0x1.370a3d70a3d71p+1, 0x1.1ccbd14f3d7ffp+0, 0x0p+0, 0x0p+0, 0x1.52faa4766c6dep+1}, {{Gauss {0x1.7414a4d2b2bfep-7, 0x1.4p+2, 0x1.999999999999ap+0}, Gauss {0x1.78359bc33f855p-5, 0x1.4p+2, 0x1.d99999999999ap+0}, Gauss {-0x1.48adeebb341e1p-6, 0x1.4p+2, 0x1.0666666666666p+1}, Gauss {-0x1.4a4d2b2bfdb4dp-10, 0x1.4p+2, 0x1.5333333333333p+1}}}}},
      {7, {Pack {Spd {-0x1.1f70a3d70a3d7p+6, -0x1.c95734b51372ap+5, 0x0p+0}, Spd {-0x1.44c927913e814p+4, -0x1.23d193708aac9p+4, 0x0p+0}, Spd {0x1.285f5ad96a6ap+1, 0x1.143760bf5d788p+1, 0x0p+0}, Spd {}, 0x1.b2e147ae147aep+3, 0x1.9f5c28f5c28f6p+3, 0x1.951eb851eb852p+3, 0x1.72e147ae147aep+3, 0x1.91eb851eb851fp+1, 0x1.004babcffd02fp+0, 0x0p+0, 0x0p+0, 0x1.7940aaeafab54p+1}, {{Gauss {0x1.9db65ecc3e319p-6, 0x1.4p+2, 0x1.8p+0}, Gauss {0x1.da5daf07bfe7ep-6, 0x1.4p+2, 0x1.0cccccccccccdp+1}, Gauss {-0x1.7c80841ede11ap-8, 0x1p+1, 0x1.3333333333333p+1}}}}},
      {4, {Pack {Spd {-0x1.12721ba64eb3cp+4, -0x1.d42606c5161f2p+3, 0x0p+0}, Spd {-0x1.1fc44da24a424p+2, -0x1.52c4d8e284c4fp+1, 0x0p+0}, Spd {0x1.7c2c110002844p-1, 0x1.9db8b76c1277dp-1, 0x0p+0}, Spd {}, 0x1.e1ab3c594ca27p+2, 0x1.0654e02c2522p+0, 0x1.11a924f227d03p+3, 0x1.2c444ae85b9e9p+3, 0x1.993d67699ba51p-2, 0x1.cecc6c54bcf0bp+0, 0x0p+0, 0x0p+0, 0x1.fde997deae76ap-2}, {{}}}},
      {9, {Pack {Spd {-0x1.10360e736049fp+7, -0x1.a38f3e0370cddp+6, 0x0p+0}, Spd {-0x1.165c7192ea52fp+6, -0x1.bec1fc8f32379p+4, 0x0p+0}, Spd {0x1.e2920c069e7fbp+1, 0x1.3f5158b827fa2p+1, 0x0p+0}, Spd {}, 0x1.0eb851eb851ecp+4, 0x1.0b5c28f5c28f6p+4, 0x1.14p+4, 0x1.dd1eb851eb852p+3, 0x1.351eb851eb852p+2, 0x1.9bb5789d4aa92p-1, 0x0p+0, 0x0p+0, 0x1.6123a29c779a7p+2}, {{Gauss {0x1.efc71d6063172p-3, 0x1.3333333333333p+2, 0x1.dc28f5c28f5c3p-1}, Gauss {0x1.d8c6d612c6ac2p-9, 0x1.2666666666666p+2, 0x1.a8f5c28f5c28fp+0}}}}},
      {20, {Pack {Spd {-0x1.89df813a27434p+3, -0x1.2f3bce4217d28p+3, 0x0p+0}, Spd {-0x1.1101e0aad022cp+2, -0x1.92c83a96d4c34p+2, 0x0p+0}, Spd {0x1.2d412711bcc0ep+0, 0x1.461b2a27f1b69p+0, 0x0p+0}, Spd {}, 0x1.9ba67a52ac754p+2, 0x1.5bc2bf9830e3dp+2, 0x1.82a0c3c4e64e8p+2, 0x1.56b5bf6a0dbadp+2, 0x1.4e16575a59e8bp-1, 0x1.0ec22e384ca2ap+1, 0x0p+0, 0x0p+0, 0x1.36b9e137bddc7p+0}, {{}}}},
      {8, {Pack {Spd {-0x1.8751eb851eb85p+6, -0x1.390cad57bc7f7p+6, 0x0p+0}, Spd {-0x1.d45d4738a3b58p+4, -0x1.d45d4738a3b58p+4, 0x0p+0}, Spd {0x1.8dd3fe1975f2dp+1, 0x1.4313b5bf6a0dcp+1, 0x0p+0}, Spd {}, 0x1.ed70a3d70a3d7p+3, 0x1.d0a3d70a3d70ap+3, 0x1.cf5c28f5c28f6p+3, 0x1.9f5c28f5c28f6p+3, 0x1.f851eb851eb85p+1, 0x1.c3c224fe113d7p-1, 0x0p+0, 0x0p+0, 0x1.1d24cc6822ff1p+2}, {{Gauss {0x1.1fb480a5accd5p-2, 0x1.4p+2, 0x1.b2224edf6124p-1}, Gauss {0x1.4d898b2e9ccb8p-4, 0x1.cp+2, 0x1.71f02c4d65e46p+0}}}}},
      {3, {Pack {Spd {-0x1.3c0f5fef53e05p+2, -0x1.8c46a931bd117p+1, 0x0p+0}, Spd {-0x1.75bad70103354p+0, -0x1.872172408f3c5p+0, 0x0p+0}, Spd {0x1.983e16bc0427bp-1, 0x1.cf2243f7a6953p-1, 0x0p+0}, Spd {}, 0x1.59985a69d8e1bp+2, 0x1.1d686833c6003p+2, 0x1.1e784a2918fep+3, 0x1.40003bc4d22c9p+3, 0x1.99906cca2db62p-2, 0x1.4282842944f2dp+1, 0x0p+0, 0x0p+0, 0x1.8d5db4e6fcf9cp+0}, {{}}}},
      {2, {Pack {Spd {-0x1.19d11ca2cdf5cp+5, 0x1.3ffe6b3fe9faep+3, 0x0p+0}, Spd {-0x1.184d5b82dd957p+4, -0x1.a0d76668eaa52p+4, 0x0p+0}, Spd {0x1.1909c220a1603p+1, 0x1.b9ae0e9ba435dp+2, 0x0p+0}, Spd {}, 0x1.0953d4feca75ep+3, 0x1.362629affcb27p+4, 0x1.607c81c63e3d5p+3, 0x1.6b412ad81adebp+3, 0x1.1065ac2c4354fp-1, 0x1.a4139385ae554p+0, 0x0p+0, 0x0p+0, 0x1.71e70633f6a79p+2}, {{Gauss {0x1.a5f676ea4228ap-3, 0x1.1054492d707b9p+0, 0x1.ffc6da4484945p-2}}}}},
      {13, {Pack {Spd {-0x1.85a848beb5b2dp+4, -0x1.25d17d6b65a9bp+4, 0x0p+0}, Spd {-0x1.eef405f6ba062p+1, -0x1.28983d790752ep+1, 0x0p+0}, Spd {0x1.843f705857affp+0, 0x1.4e6cc1ca3a4b5p+0, 0x0p+0}, Spd {}, 0x1.02e147ae147aep+3, 0x1.7eb851eb851ecp+2, 0x1.a851eb851eb85p+2, 0x1.599999999999ap+2, 0x1.6666666666666p-1, 0x1.ae89e01325a1ap+0, 0x0p+0, 0x0p+0, 0x1.fa018a43bb40bp+0}, {{Gauss {0x1.70a3d70a3d70ap-4, 0x1.8c8ee49f51698p+3, 0x1.06734f82f5126p+1}}}}},
      {12, {Pack {Spd {-0x1.d5677849bdb93p+3, -0x1.7c0b5adcc5685p+3, 0x0p+0}, Spd {-0x1.303504c48adefp+0, -0x1.523d18faa2c8fp+2, 0x0p+0}, Spd {0x1.034cf14a5a972p+0, 0x1.2e089fe1b2372p+0, 0x0p+0}, Spd {}, 0x1.abac71e3722acp+2, 0x1.29b6f3b213e3ep+3, 0x1.c6ca17e6a692ap+2, 0x1.2f456fe1396b6p+3, 0x1.92c307512d194p-1, 0x1.049d3dbdfba3ap+1, 0x0p+0, 0x0p+0, 0x1.7778705425f2p+2}, {{Gauss {0x1.00004d2cd97cep+0, 0x1.800024e8ed94cp+1, 0x1.000024122dfffp+1}}}}},
      {1, {Pack {Spd {-0x1.6caf87ad080b6p+3, 0x0p+0, 0x0p+0}, Spd {-0x1.8b1f53825e13bp+2, 0x0p+0, 0x0p+0}, Spd {0x1.3025e13b18dacp+0, 0x0p+0, 0x0p+0}, Spd {}, 0x1.9b22d0e560419p+3, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x1.0f18e350c7c3ap+0, 0x0p+0, 0x0p+0, 0x1.70effe2a3cea7p+1}, {{Gauss {0x1.f6f8f041461b7p-4, 0x1.4p+2, 0x1.3333333333333p+0}, Gauss {0x1.4d940789613d3p-8, 0x1.4p+2, 0x1.ccccccccccccdp+0}, Gauss {-0x1.2c6ac215b9a5bp-6, 0x1p+1, 0x1.0cccccccccccdp+1}}}}}
    }, {}
  };
  // clang-format on
}

} // namespace nddo
} // namespace Sparrow
} // namespace Scine
