/**
 * @file
 * @copyright This code is licensed under the 3-clause BSD license.\n
 *            Copyright ETH Zurich, Department of Chemistry and Applied Biosciences, Reiher Group.\n
 *            See LICENSE.txt for details.
 *
 * @note This file was generated by the Embed binary from runtime values.
 *   Prefer improving the generator over editing this file whenever possible.
 *
 */
#ifndef INCLUDE_SPARROW_IMPLEMENTATIONS_DFTB_PARAMS_TRANS3D_0_1_PARAMETER_SET_H
#define INCLUDE_SPARROW_IMPLEMENTATIONS_DFTB_PARAMS_TRANS3D_0_1_PARAMETER_SET_H

#include "Sparrow/Implementations/Dftb/ParameterSet.h"

namespace Scine {
namespace Sparrow {
namespace dftb {

/*! @brief Dftb trans3d-0-1 parameter set generator
 *
 * @param elements Elements for which to load parameters. If empty, loads all
 *   available parameters.
 */
ParameterSet params_trans3d_0_1(const std::vector<int>& elements = {});

// NOTE: Atom-pair data generator fns
SkfData params_trans3d_0_1_ti_n();
SkfData params_trans3d_0_1_ti_h();
SkfData params_trans3d_0_1_sc_o();
SkfData params_trans3d_0_1_sc_h();
SkfData params_trans3d_0_1_fe_o();
SkfData params_trans3d_0_1_fe_h();
SkfData params_trans3d_0_1_ti_c();
SkfData params_trans3d_0_1_co_o();
SkfData params_trans3d_0_1_fe_n();
SkfData params_trans3d_0_1_sc_c();
SkfData params_trans3d_0_1_o_co();
SkfData params_trans3d_0_1_co_n();
SkfData params_trans3d_0_1_co_h();
SkfData params_trans3d_0_1_ni_h();
SkfData params_trans3d_0_1_c_fe();
SkfData params_trans3d_0_1_c_co();
SkfData params_trans3d_0_1_n_ni();
SkfData params_trans3d_0_1_c_ni();
SkfData params_trans3d_0_1_co_c();
SkfData params_trans3d_0_1_fe_c();
SkfData params_trans3d_0_1_c_sc();
SkfData params_trans3d_0_1_c_ti();
SkfData params_trans3d_0_1_ti_o();
SkfData params_trans3d_0_1_co_co();
SkfData params_trans3d_0_1_h_ni();
SkfData params_trans3d_0_1_h_ti();
SkfData params_trans3d_0_1_h_sc();
SkfData params_trans3d_0_1_o_sc();
SkfData params_trans3d_0_1_n_co();
SkfData params_trans3d_0_1_sc_sc();
SkfData params_trans3d_0_1_h_co();
SkfData params_trans3d_0_1_fe_fe();
SkfData params_trans3d_0_1_o_ti();
SkfData params_trans3d_0_1_n_fe();
SkfData params_trans3d_0_1_ti_ti();
SkfData params_trans3d_0_1_ni_ni();
SkfData params_trans3d_0_1_ni_c();
SkfData params_trans3d_0_1_n_ti();
SkfData params_trans3d_0_1_sc_n();
SkfData params_trans3d_0_1_ni_n();
SkfData params_trans3d_0_1_n_sc();
SkfData params_trans3d_0_1_ni_o();
SkfData params_trans3d_0_1_o_fe();
SkfData params_trans3d_0_1_h_fe();
SkfData params_trans3d_0_1_o_ni();

// Spin constants
SkfSpinConstants params_trans3d_0_1_spin();

} // namespace dftb
} // namespace Sparrow
} // namespace Scine

#endif
