/**
 * @file
 * @copyright This code is licensed under the 3-clause BSD license.\n
 *            Copyright ETH Zurich, Department of Chemistry and Applied Biosciences, Reiher Group.\n
 *            See LICENSE.txt for details.
 *
 * @note This file was generated by the Embed binary from runtime values.
 *   Prefer improving the generator over editing this file whenever possible.
 *
 * This file contains functions generating runtime values. It was
 * generated from runtime values of its return type. It is not intended to be
 * human-readable. A small guide: Return values are directly brace-initialized
 * in deep nesting to keep file size to a minimum. Types are annotated only when
 * necessary. Floating point values are represented in hexadecimal (see
 * std::hexfloat) to ensure serialization does not cause loss of accuracy.
 *
 * The functions defined here might be declared and called elsewhere entirely.
 *
 */
#include "Sparrow/Implementations/Nddo/Parameters.h"

namespace Scine {
namespace Sparrow {
namespace nddo {

Parameters rm1() {
  // clang-format off
  using Pack = Parameters::Atomic::Pack;
  using Spd = Parameters::Atomic::Pack::Spd;
  using Gauss = Parameters::Atomic::GaussianRepulsion;

  return {
    {
      {17, {Pack {Spd {-0x1.d9e46c409afacp+6, -0x1.3169c85dd2433p+6, 0x0p+0}, Spd {-0x1.3ec9f34e40d5bp+4, -0x1.70f0739b024f6p+3, 0x0p+0}, Spd {0x1.eeb564d13af09p+1, 0x1.e55bc29e75a17p+0, 0x0p+0}, Spd {}, 0x1.eb870329802c1p+3, 0x1.9214b23eac0d4p+3, 0x1.a9d0950e199e3p+3, 0x1.353f3fb0eff77p+3, 0x1.c3d06bbdbe3c1p+0, 0x1.c58428184cfdep-1, 0x0p+0, 0x0p+0, 0x1.d8c7805cb1b1cp+1}, {{Gauss {0x1.092824e237982p-3, 0x1.7d1656839a53dp+1, 0x1.77adef91f3b2fp+0}, Gauss {0x1.7aaac1094a2bap-9, 0x1.c64a27001f09bp+2, 0x1.4000e42b8e234p+1}}}}},
      {6, {Pack {Spd {-0x1.9dcdf28efe352p+5, -0x1.3b4220f1e80f5p+5, 0x0p+0}, Spd {-0x1.eeb2c8dfd8425p+3, -0x1.078e0510e0f8dp+3, 0x0p+0}, Spd {0x1.d9a5ebb7739f3p+0, 0x1.c4af5e26fcc41p+0, 0x0p+0}, Spd {}, 0x1.a1b331f113d3fp+3, 0x1.5e6fb7b360144p+3, 0x1.6ab6a1b26ccf3p+3, 0x1.372a9b499d02p+3, 0x1.8d59c99ff1a27p+0, 0x1.0ad6484b9e391p+0, 0x0p+0, 0x0p+0, 0x1.657b26e7cb55dp+1}, {{Gauss {0x1.31a79280a0a45p-4, 0x1.6f4f50a02b841p+2, 0x1.0b419ad502fc3p+0}, Gauss {0x1.81b21c475e636p-7, 0x1.bb2319751c0bdp+2, 0x1.a95e55f6ac9a2p+0}, Gauss {0x1.30cbe54640563p-5, 0x1.90bde1777ebcap+2, 0x1.a1afb2e0927c7p+0}, Gauss {-0x1.62c26cf77a1f8p-9, 0x1.20004e3948f6fp+3, 0x1.65d5885d31338p+1}}}}},
      {16, {Pack {Spd {-0x1.b9578df0eeebp+5, -0x1.743c03d725156p+5, 0x0p+0}, Spd {-0x1.f5880ca95bae8p+0, -0x1.18c71e6cd2913p+3, 0x0p+0}, Spd {0x1.1114a9db303cep+1, 0x1.dfe6362a5e786p+0, 0x0p+0}, Spd {}, 0x1.8fa005fa15047p+3, 0x1.10bc83085d9c9p+3, 0x1.12361d282ef33p+3, 0x1.eacae21101bp+2, 0x1.f1e49da3ea557p+1, 0x1.16e7ee106959bp+0, 0x0p+0, 0x0p+0, 0x1.38570b7f90031p+1}, {{Gauss {-0x1.7df519f2f04dp-1, 0x1.33dd441355476p+2, 0x1.3006b957a5028p-1}, Gauss {-0x1.0b07b5d6e702p-4, 0x1.cd497594d793p+2, 0x1.4b7fe2386edc5p+0}, Gauss {-0x1.ade72e77e28fbp-8, 0x1.200003c65e1dcp+3, 0x1.ccf4384ba0e84p+0}}}}},
      {1, {Pack {Spd {-0x1.7ebdddb1209eep+3, 0x0p+0, 0x0p+0}, Spd {-0x1.70fd0bc45960cp+2, 0x0p+0, 0x0p+0}, Spd {0x1.152a1a85bd43cp+0, 0x0p+0, 0x0p+0}, Spd {}, 0x1.bf767b1c0010cp+3, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x1.f22d4b67b26bdp-1, 0x0p+0, 0x0p+0, 0x1.88c0010c6f7a1p+1}, {{Gauss {0x1.a56eb9f1feb58p-4, 0x1.79b5d320a3e47p+2, 0x1.2ccd92c56a02p+0}, Gauss {0x1.087f455a7d242p-4, 0x1.9abe2a073a86ep+2, 0x1.f03deb1d19ec4p+0}, Gauss {-0x1.243d973a43c8bp-5, 0x1.67016f6bc8a5fp+1, 0x1.a2f5191c30b83p+0}}}}},
      {35, {Pack {Spd {-0x1.c5ef98eccb6fdp+6, -0x1.30bfb168c338p+6, 0x0p+0}, Spd {-0x1.5765e2b2e81f4p+0, -0x1.0678e9c0f959fp+3, 0x0p+0}, Spd {0x1.6ed213c90aa07p+2, 0x1.04076625cec6ap+1, 0x0p+0}, Spd {}, 0x1.11d99f93ae9e1p+4, 0x1.5788e97ddd7b7p+3, 0x1.f3f9628cbd124p+3, 0x1.1b89b951c5c57p+3, 0x1.1e18a94431884p+1, 0x1.9700c8d2c22f4p-1, 0x0p+0, 0x0p+0, 0x1.6efd4e74d8193p+1}, {{Gauss {0x1.f94ae0cee250cp-1, 0x1.123ad98541f3cp+2, 0x1.0006748e4756p+1}, Gauss {-0x1.dac8b43958106p-1, 0x1.2290540b1a0f7p+2, 0x1.02121682f9442p+1}}}}},
      {7, {Pack {Spd {-0x1.1b67aab97c8dfp+6, -0x1.cfd1877c60a3bp+5, 0x0p+0}, Spd {-0x1.4df09f1f14984p+4, -0x1.0abf5be5d9e41p+4, 0x0p+0}, Spd {0x1.2feeaf75a3f11p+1, 0x1.fa667224e08a2p+0, 0x0p+0}, Spd {}, 0x1.a2cbac05ace83p+3, 0x1.b66033467e699p+3, 0x1.a6cae6e3cf47dp+3, 0x1.7e1cfede97d07p+3, 0x1.400023a6ce358p+2, 0x1.0a2393580c05ap+0, 0x0p+0, 0x0p+0, 0x1.7b6bbce77c7b8p+1}, {{Gauss {0x1.f188029860b47p-5, 0x1.25b1055b89939p+2, 0x1.60f506a7b9eddp+0}, Gauss {0x1.8f889e9f92d7ep-6, 0x1.2825c4b5a7166p+2, 0x1.0ab6e935b91f7p+1}, Gauss {-0x1.761dfeee88087p-6, 0x1.06c0668cfcd32p+1, 0x1.de1d897dc2a38p+0}}}}},
      {8, {Pack {Spd {-0x1.83cc44ab2abb9p+6, -0x1.37904fe6c8209p+6, 0x0p+0}, Spd {-0x1.dd9dbedd20012p+4, -0x1.d26a8cb65c48p+4, 0x0p+0}, Spd {0x1.96f5911134dbbp+1, 0x1.46dcfd9c78713p+1, 0x0p+0}, Spd {}, 0x1.c013e3ace3228p+3, 0x1.c4a5148c7efeep+3, 0x1.de999a70592e7p+3, 0x1.968110a137f39p+3, 0x1.f751662421478p+1, 0x1.f17e493121602p-1, 0x0p+0, 0x0p+0, 0x1.0b0182b6ff053p+2}, {{Gauss {0x1.d8f4b61fe21d9p-3, 0x1.4df86bb7083f7p+2, 0x1.cea9534b00af5p-1}, Gauss {0x1.e00a6182d1d6fp-5, 0x1.db7a2199adbb9p+2, 0x1.847de6b5ac1edp+0}}}}},
      {53, {Pack {Spd {-0x1.2b9993f00c6cfp+6, -0x1.9b482adc4c9c9p+5, 0x0p+0}, Spd {-0x1.0c5cc20d5629ep+2, -0x1.199fe4a1d5a84p+2, 0x0p+0}, Spd {0x1.43d844d013a93p+1, 0x1.28a02173174edp+1, 0x0p+0}, Spd {}, 0x1.3ffef0bbbf5e5p+4, 0x1.d38335aa05f86p+2, 0x1.ec22064fa559cp+2, 0x1.b6abf7d58f133p+2, 0x1.6a80e71b2cac3p+0, 0x1.5c4f69f59212ep-1, 0x0p+0, 0x0p+0, 0x1.121efec8c85b5p+1}, {{Gauss {-0x1.4dbb0955ea176p-4, 0x1.8f86cde4fac1p+0, 0x1.0000acce29c42p+1}, Gauss {0x1.e48e54c1f9343p-5, 0x1.70b6120ac47f2p+2, 0x1.1a39c51dabe27p+1}}}}},
      {9, {Pack {Spd {-0x1.0c5e0d6395d19p+7, -0x1.af62ed85a9f89p+6, 0x0p+0}, Spd {-0x1.1800015641553p+6, -0x1.05704930cb79ep+5, 0x0p+0}, Spd {0x1.19d0f69298f46p+2, 0x1.52ff484a1badp+1, 0x0p+0}, Spd {}, 0x1.0b88dc4794134p+4, 0x1.e739d685b332cp+3, 0x1.0c2ecd580d075p+4, 0x1.dbb48684e9df3p+3, 0x1.ff66c1d5f8c58p+0, 0x1.a09c61caf632fp-1, 0x0p+0, 0x0p+0, 0x1.800002843ebe8p+2}, {{Gauss {0x1.9cb15a807f166p-2, 0x1.cd1535f22a546p+2, 0x1.a2103bb766334p-1}, Gauss {0x1.223c5012670adp-4, 0x1.200020b72fac9p+3, 0x1.702253e7dea11p+0}}}}},
      {15, {Pack {Spd {-0x1.4e85ccadc31c5p+5, -0x1.131141489facp+5, 0x0p+0}, Spd {-0x1.88a64aed641c1p+2, -0x1.7c7166094954ep+2, 0x0p+0}, Spd {0x1.0faad7af7ede3p+1, 0x1.be4790b849881p+0, 0x0p+0}, Spd {}, 0x1.629436eea9966p+3, 0x1.e6aad022c2a2ap+2, 0x1.6bbcb1cc96463p+2, 0x1.d9c50c0e2b3bfp+2, 0x1.296ce5dc684b4p+0, 0x1.3a56a92f0ddf9p+0, 0x0p+0, 0x0p+0, 0x1.e8f15ccf0defbp+0}, {{Gauss {-0x1.a47d6c3c693cep-2, 0x1.859a104c7e5ddp+2, 0x1.5106507c19561p+0}, Gauss {-0x1.4dcf38b7d7724p-3, 0x1.c60ffda4052d6p+2, 0x1.e83f1fd07fdfbp+0}, Gauss {-0x1.905a8b66d0ef7p-5, 0x1.1ffe4e196886dp+3, 0x1.544c47006f919p+1}}}}}
    }, {}
  };
  // clang-format on
}

} // namespace nddo
} // namespace Sparrow
} // namespace Scine
