/**
 * @file
 * @copyright This code is licensed under the 3-clause BSD license.\n
 *            Copyright ETH Zurich, Department of Chemistry and Applied Biosciences, Reiher Group.\n
 *            See LICENSE.txt for details.
 *
 * @note This file was generated by the Embed binary from runtime values.
 *   Prefer improving the generator over editing this file whenever possible.
 *
 * This file contains functions generating runtime values. It was
 * generated from runtime values of its return type. It is not intended to be
 * human-readable. A small guide: Return values are directly brace-initialized
 * in deep nesting to keep file size to a minimum. Types are annotated only when
 * necessary. Floating point values are represented in hexadecimal (see
 * std::hexfloat) to ensure serialization does not cause loss of accuracy.
 *
 * The functions defined here might be declared and called elsewhere entirely.
 *
 */
#include "Utils/DataStructures/AtomicGtos.h"
#include <unordered_map>

namespace Scine {
namespace Sparrow {
namespace Sto6g {

std::unordered_map<int, Utils::AtomicGtos> rm1() {
  // clang-format off
  return {
    {17, {Utils::GtoExpansion {0, {{{0, 0x1.8720d365f48b7p+5, -0x1.6db654971c2c9p-4}, {0, 0x1.b7ca4d5b28ff8p+3, -0x1.25c5612593327p-2}, {0, 0x1.578668c211ae9p+2, -0x1.98a73e2284d34p-2}, {0, 0x1.4a44868e780a8p+0, 0x1.e8f1f8f428082p-2}, {0, 0x1.6ee76cab9e2edp-1, 0x1.1d15927583cebp-2}, {0, 0x1.a0c701fd0ff03p-2, 0x1.add27e0419dccp-6}}}}, Utils::GtoExpansion {1, {{{1, 0x1.240c887d73923p+4, -0x1.6ec0fe7cbef16p-3}, {1, 0x1.34733cee999b2p+2, -0x1.27e8b25307481p-3}, {1, 0x1.9dce065770e53p-1, 0x1.6ebdfb27d424fp-3}, {1, 0x1.a0930b6c154b1p-2, 0x1.a96905c6ea2fep-3}, {1, 0x1.bf52f070d9537p-3, 0x1.54c4e47fc78d8p-4}, {1, 0x1.e823cfc82e9fbp-4, 0x1.e4ca572d4396fp-8}}}}, boost::none}},
    {16, {Utils::GtoExpansion {0, {{{0, 0x1.dcb80866f84a5p+3, -0x1.2bf9097fa839ep-5}, {0, 0x1.0c03ca57149d3p+2, -0x1.e1ed555f172eep-4}, {0, 0x1.a2b2dc5ae07b8p+0, -0x1.4f31e4c4c3c62p-3}, {0, 0x1.928a4b067ed11p-2, 0x1.910dc2f4a172bp-3}, {0, 0x1.bf3193f14f478p-3, 0x1.d3ad35b2faa6dp-4}, {0, 0x1.fbfb17ee0a065p-4, 0x1.608efe6525276p-7}}}}, Utils::GtoExpansion {1, {{{1, 0x1.1d84218e3a2ffp+4, -0x1.648721a57d2f2p-3}, {1, 0x1.2d8cea591e132p+2, -0x1.1fa8850fd0cb9p-3}, {1, 0x1.948c650cb7a2ep-1, 0x1.648433d2481d6p-3}, {1, 0x1.97418df7b856cp-2, 0x1.9d8c799cbf2a5p-3}, {1, 0x1.b5515d0533b7fp-3, 0x1.4b4481e09051ap-4}, {1, 0x1.dd388179be6cdp-4, 0x1.d745f11af1252p-8}}}}, boost::none}},
    {15, {Utils::GtoExpansion {0, {{{0, 0x1.d7cc09027454ap+3, -0x1.29a5a19d12f88p-5}, {0, 0x1.093f691d01eecp+2, -0x1.de30c5d7808d5p-4}, {0, 0x1.9e6036d1c1aedp+0, -0x1.4c9893a1c8bddp-3}, {0, 0x1.8e625ab1fe46dp-2, 0x1.8df1b93db70a6p-3}, {0, 0x1.ba939e0422f27p-3, 0x1.d00cef34c143ap-4}, {0, 0x1.f6bc77f34f4d6p-4, 0x1.5dd33654a126dp-7}}}}, Utils::GtoExpansion {1, {{{1, 0x1.edd39ae3ba466p+3, -0x1.2953f44100369p-3}, {1, 0x1.04c79acf0266p+2, -0x1.dfc9a8a7b387fp-4}, {1, 0x1.5dda1a4041018p-1, 0x1.295182ef207f5p-3}, {1, 0x1.60318b69f26cp-2, 0x1.58e178cb1ed3dp-3}, {1, 0x1.7a30d9f21c642p-3, 0x1.144315c48d998p-4}, {1, 0x1.9cb2de512b387p-4, 0x1.8905343d75c47p-8}}}}, boost::none}},
    {35, {Utils::GtoExpansion {0, {{{0, 0x1.a8ce8f98a34b1p+6, 0x1.098c66343a615p-5}, {0, 0x1.7b0d162ef0115p+3, -0x1.93d6fe1ce9446p-2}, {0, 0x1.692ebba517133p+2, -0x1.a248c4a4ea21fp-1}, {0, 0x1.bbd7d25f9784dp+0, 0x1.aec0ba8f572dfp-1}, {0, 0x1.0a09687b116c3p+0, 0x1.49b4a6f8a448p-2}, {0, 0x1.3b375e2d4929p-1, 0x1.93b61fb97baafp-7}}}}, Utils::GtoExpansion {1, {{{1, 0x1.3b969556a713bp+3, -0x1.53f96726d672bp-5}, {1, 0x1.a487f2026af19p+1, -0x1.ac0903cb8d95bp-4}, {1, 0x1.68d8c5f49e9e8p+0, -0x1.0b27667d4cf8ep-3}, {1, 0x1.75e320d50d9c4p-2, 0x1.4fd292a77f189p-3}, {1, 0x1.a310acdf723f2p-3, 0x1.b49f47e6528d3p-4}, {1, 0x1.dc2abf3736459p-4, 0x1.7e0bc30a72c14p-7}}}}, boost::none}},
    {9, {Utils::GtoExpansion {0, {{{0, 0x1.0c66f7953880fp+9, -0x1.51df92c8893e9p-2}, {0, 0x1.89c72464f4f46p+6, -0x1.d776f16bed0a1p-2}, {0, 0x1.baa3ed50c7f29p+4, -0x1.c568f70f4d38bp-2}, {0, 0x1.fa636ee49bcf6p+1, 0x1.56874228e8a74p-1}, {0, 0x1.cba910a3c55cdp+0, 0x1.3e2914dec665ap-1}, {0, 0x1.b66b3d4f5c5dbp-1, 0x1.bd223eaeabd75p-4}}}}, Utils::GtoExpansion {1, {{{1, 0x1.4949443c5c2fp+5, 0x1.2d77e6fcb2233p+0}, {1, 0x1.577c0d305b14ep+3, 0x1.6cb3587aa639ep+0}, {1, 0x1.eb9bb41446898p+1, 0x1.7475ac7c8e70ep+0}, {1, 0x1.9b00d5d8df10cp+0, 0x1.0b12394ce5ae2p+0}, {1, 0x1.77e09bee321p-1, 0x1.8dfab65af8ea5p-2}, {1, 0x1.6367333bc4979p-2, 0x1.4733108955c1p-5}}}}, boost::none}},
    {8, {Utils::GtoExpansion {0, {{{0, 0x1.17d9afc5a3dd4p+8, -0x1.9e96677547f83p-3}, {0, 0x1.9a92dafce5cc9p+5, -0x1.21415f5b86dfcp-2}, {0, 0x1.cd852cfe9e6d1p+3, -0x1.162dac5470929p-2}, {0, 0x1.07fe60b719b9cp+1, 0x1.a44ca9542bef1p-2}, {0, 0x1.df44287cec40cp-1, 0x1.86661b0dcd76fp-2}, {0, 0x1.c91e64d179f64p-2, 0x1.1119c9033424ap-4}}}}, Utils::GtoExpansion {1, {{{1, 0x1.3222a69f78096p+5, 0x1.13362a0aaf893p+0}, {1, 0x1.3f55e35c9ba5bp+3, 0x1.4cefbd98275f1p+0}, {1, 0x1.c90b8e3a54446p+1, 0x1.5405111dae305p+0}, {1, 0x1.7e1b720a57fb9p+0, 0x1.e79edb2b25302p-1}, {1, 0x1.5d736d8fe374ap-1, 0x1.6b511a09a4b41p-2}, {1, 0x1.4a6a85b25dd14p-2, 0x1.2ab39bdd74f5ep-5}}}}, boost::none}},
    {7, {Utils::GtoExpansion {0, {{{0, 0x1.382e992b4241ep+7, -0x1.0b94bc2c6a7b9p-3}, {0, 0x1.ca02112a59dbp+4, -0x1.75612648f55ep-3}, {0, 0x1.016b98c5ebcf3p+3, -0x1.6714be6dcd79ep-3}, {0, 0x1.267e4f26e2089p+0, 0x1.0f447f72050f3p-2}, {0, 0x1.0b51849d75f8p-1, 0x1.f7f04401ee2d5p-3}, {0, 0x1.fdee3b6ef0e8ap-3, 0x1.6086cf3cf39a3p-5}}}}, Utils::GtoExpansion {1, {{{1, 0x1.6f665f02a0d47p+4, 0x1.22b2876e9c8dep-1}, {1, 0x1.7f3dde8e4d43fp+2, 0x1.5fab9edbcf56p-1}, {1, 0x1.12414ac7f7e85p+1, 0x1.6726faf67dcep-1}, {1, 0x1.ca934df856d42p-1, 0x1.018776ac8ce19p-1}, {1, 0x1.a36242b526eadp-2, 0x1.7fc29a8cc8611p-3}, {1, 0x1.8c8a2d6b4b67ep-3, 0x1.3b8257a8792b7p-6}}}}, boost::none}},
    {6, {Utils::GtoExpansion {0, {{{0, 0x1.7b158c295ea8dp+6, -0x1.701807ba594fp-4}, {0, 0x1.1614aabb29fd4p+4, -0x1.00d127537b05ep-3}, {0, 0x1.38963473ab85ep+2, -0x1.edf6ec852602p-4}, {0, 0x1.659ad2df1354fp-1, 0x1.752a4db883f14p-3}, {0, 0x1.449b286f8725p-2, 0x1.5a9e29bc4498fp-3}, {0, 0x1.359b09a650218p-3, 0x1.e4f2b2bb95ea8p-6}}}}, Utils::GtoExpansion {1, {{{1, 0x1.2597713dd885cp+4, 0x1.b743e5763415ep-2}, {1, 0x1.32403773c5535p+2, 0x1.09b331893cd04p-1}, {1, 0x1.b65160c6b2d07p+0, 0x1.0f5a518e87167p-1}, {1, 0x1.6e73546b4e25dp-1, 0x1.852544dd03527p-2}, {1, 0x1.4f21dc6422821p-2, 0x1.21f1eab339e8ap-3}, {1, 0x1.3ce09ee5d0fa8p-3, 0x1.dcc1f4a940693p-7}}}}, boost::none}},
    {53, {Utils::GtoExpansion {0, {{{0, 0x1.20d7ec4e3e33dp+3, 0x1.47cfb726aeb02p-7}, {0, 0x1.a00cf8c86b5a4p+1, 0x1.057e572212d92p-5}, {0, 0x1.2ed0de1d6f091p+0, -0x1.3d7d87e97937bp-4}, {0, 0x1.5bc03568d51dep-1, -0x1.1bf79f2a6574ap-2}, {0, 0x1.e10fcd8f3aeedp-3, 0x1.0bd17908dc4cfp-2}, {0, 0x1.222f57c476df5p-3, 0x1.a2876535d2a42p-5}}}}, Utils::GtoExpansion {1, {{{1, 0x1.44ad24e30cb7dp+4, 0x1.d4028a517d2f3p-8}, {1, 0x1.e10e7041b9d67p+0, -0x1.772ebba37e6abp-4}, {1, 0x1.cecda29a87ee5p-1, -0x1.6355bd8cc7dd5p-3}, {1, 0x1.292dcf7718673p-2, 0x1.62d2406359504p-3}, {1, 0x1.6e1ffb40d8eeep-3, 0x1.43a80379a000dp-4}, {1, 0x1.c5f87c698d0e1p-4, 0x1.67b9c57b51afbp-8}}}}, boost::none}},
    {1, {Utils::GtoExpansion {0, {{{0, 0x1.b14ba282944b5p+4, 0x1.3d90ea057c2b2p-4}, {0, 0x1.3dc6e877b471cp+2, 0x1.df4efd20b0733p-4}, {0, 0x1.639c35bd892a1p+0, 0x1.3ac46139c4511p-3}, {0, 0x1.e8a59499de092p-2, 0x1.368b45c628cc3p-3}, {0, 0x1.7b82feedf337bp-3, 0x1.5765dc7207454p-4}, {0, 0x1.389b95c546de5p-4, 0x1.b9f9a552d8aefp-7}}}}, boost::none, boost::none}},
  };
  // clang-format on
}

} // namespace Sto6g
} // namespace Sparrow
} // namespace Scine
